import React from "react";
import { Metadata } from "next";
import { notFound } from "next/navigation";
import BlogPostClient from "./BlogPostClient";
import { api } from "../../../../convex/_generated/api";
import { ConvexHttpClient } from "convex/browser";

const convex = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL!);
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://www.sleads.nl";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = await convex.query(api.blog.getBlogPostBySlug, {
    slug,
  });

  if (!post) {
    return {
      title: "Post Not Found | Sleads",
      robots: { index: false, follow: false },
    };
  }

  const metaTitle = post.metaTitle || post.title;
  const metaDescription = post.metaDescription || post.excerpt;
  const fullUrl = `${BASE_URL}/blog/${slug}`;

  // Ensure image URL is absolute
  const imageUrl = post.image?.startsWith("http")
    ? post.image
    : post.image
      ? `${BASE_URL}${post.image}`
      : `${BASE_URL}/images/og/blog-og.jpg`;

  return {
    title: `${metaTitle} | Sleads Blog`,
    description: metaDescription,
    keywords: post.keywords
      ? post.keywords.split(",").map((k) => k.trim())
      : undefined,
    authors: post.author ? [{ name: post.author }] : [{ name: "Sleads Team" }],
    creator: "Sleads",
    publisher: "Sleads",
    alternates: {
      canonical: fullUrl,
    },
    openGraph: {
      title: metaTitle,
      description: metaDescription,
      url: fullUrl,
      siteName: "Sleads",
      locale: "en_US",
      type: "article",
      publishedTime: post.date ? new Date(post.date).toISOString() : undefined,
      modifiedTime: post.date ? new Date(post.date).toISOString() : undefined,
      authors: post.author ? [post.author] : ["Sleads Team"],
      section: post.category,
      tags: post.tags,
      // OG image is dynamically generated by opengraph-image.tsx
      // Fallback image for crawlers that don't support dynamic images
      images: [
        {
          url: imageUrl,
          width: 1200,
          height: 630,
          alt: post.title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: metaTitle,
      description: metaDescription,
      // Twitter image is dynamically generated by twitter-image.tsx
      creator: "@sleads_nl",
      site: "@sleads_nl",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
  };
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = await convex.query(api.blog.getBlogPostBySlug, {
    slug,
  });

  if (!post) {
    notFound();
  }

  const fullUrl = `${BASE_URL}/blog/${slug}`;

  // Ensure image URL is absolute
  const imageUrl = post.image?.startsWith("http")
    ? post.image
    : post.image
      ? `${BASE_URL}${post.image}`
      : `${BASE_URL}/images/og/blog-og.jpg`;

  // Calculate word count for reading time estimation
  const wordCount = post.content
    .replace(/<[^>]*>/g, " ")
    .split(/\s+/)
    .filter((w) => w).length;

  // JSON-LD Article structured data
  const articleJsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: post.title,
    description: post.excerpt,
    image: [imageUrl],
    datePublished: post.date
      ? new Date(post.date).toISOString()
      : new Date().toISOString(),
    dateModified: post.date
      ? new Date(post.date).toISOString()
      : new Date().toISOString(),
    author: {
      "@type": "Person",
      name: post.author || "Sleads Team",
      url: BASE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: "Sleads",
      url: BASE_URL,
      logo: {
        "@type": "ImageObject",
        url: `${BASE_URL}/images/logo/logo.png`,
      },
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": fullUrl,
    },
    articleSection: post.category,
    keywords: post.keywords || post.tags?.join(", "),
    wordCount: wordCount,
    inLanguage: "en-US",
  };

  // JSON-LD BreadcrumbList for navigation
  const breadcrumbJsonLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: BASE_URL,
      },
      {
        "@type": "ListItem",
        position: 2,
        name: "Blog",
        item: `${BASE_URL}/blog`,
      },
      {
        "@type": "ListItem",
        position: 3,
        name: post.title,
        item: fullUrl,
      },
    ],
  };

  // JSON-LD Organization for site-wide info
  const organizationJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Sleads",
    url: BASE_URL,
    logo: `${BASE_URL}/images/logo/logo.png`,
    sameAs: [
      "https://www.linkedin.com/company/sleads",
      "https://twitter.com/sleads_nl",
    ],
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer service",
      url: `${BASE_URL}/contact`,
    },
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articleJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }}
      />
      <BlogPostClient post={post} />
    </>
  );
}
