import React from "react";
import { Metadata } from "next";
import BlogPageClient from "./BlogPageClient";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "https://www.sleads.nl";

export const metadata: Metadata = {
  title: "Blog | Sleads - Web Development & Digital Strategy Insights",
  description:
    "Read our latest insights on web development, SaaS solutions, digital experiences, UX/CRO, AI automation, and technology trends. Expert articles from the Sleads team.",
  keywords: [
    "Web Development Blog",
    "SaaS Development Articles",
    "Digital Agency Blog",
    "Technology Insights",
    "Web Design Blog",
    "UX Design",
    "SEO Tips",
    "AI Automation",
    "Business Strategy",
  ],
  alternates: {
    canonical: `${BASE_URL}/blog`,
  },
  openGraph: {
    title: "Blog | Sleads - Web Development & Digital Strategy Insights",
    description:
      "Read our latest insights on web development, SaaS solutions, UX design, SEO, AI automation, and digital experiences. Expert articles from the Sleads team.",
    url: `${BASE_URL}/blog`,
    siteName: "Sleads",
    locale: "en_US",
    type: "website",
    // OG image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Blog | Sleads - Web Development & Digital Strategy Insights",
    description:
      "Read our latest insights on web development, SaaS solutions, UX design, SEO, and AI automation.",
    // Twitter image is auto-generated by twitter-image.tsx
    creator: "@sleads_nl",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

// JSON-LD structured data for the blog listing page
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "Blog",
  name: "Sleads Blog",
  description:
    "Expert insights on web development, SaaS solutions, digital experiences, UX/CRO, AI automation, and technology trends.",
  url: `${BASE_URL}/blog`,
  publisher: {
    "@type": "Organization",
    name: "Sleads",
    url: BASE_URL,
    logo: {
      "@type": "ImageObject",
      url: `${BASE_URL}/images/logo/logo.png`,
    },
  },
};

export default function BlogPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <BlogPageClient />
    </>
  );
}
